/**
 * Core domain model for Fix My Problem.
 *
 * The Case — not the chat transcript — is the source of truth. Every fact,
 * piece of evidence, research finding and action is a first-class record that
 * can be inspected, corrected and audited by the user.
 */

export type Timestamp = string; // ISO-8601 UTC

/**
 * A reference to a string in the catalogue, stored instead of rendered text.
 *
 * System-generated case entries are recorded this way so a case reads correctly
 * in whichever language the interface is set to, without ever rewriting the
 * stored record. User- and model-authored text is stored verbatim instead - it
 * is content, not presentation.
 */
export interface LocalizedText {
  key: string;
  params?: Record<string, string | number>;
  /** Selects a plural form when the key has `_one` / `_other` variants. */
  count?: number;
}

export type CaseStatus =
  | "NEW"
  | "INTAKE"
  | "INVESTIGATING"
  | "INFORMATION_REQUIRED"
  | "READY_FOR_ACTION"
  | "AWAITING_USER_APPROVAL"
  | "ACTION_IN_PROGRESS"
  | "WAITING_FOR_RESPONSE"
  | "FOLLOW_UP_REQUIRED"
  | "ESCALATION_AVAILABLE"
  | "RESOLVED"
  | "CLOSED";

export type RiskLevel = "LOW" | "MEDIUM" | "HIGH";

export type Confidence = "HIGH" | "MEDIUM" | "LOW";

export type FactVerification =
  | "USER_REPORTED"
  | "DOCUMENT_VERIFIED"
  | "SYSTEM_VERIFIED"
  | "EXTERNAL_SOURCE"
  | "INFERRED"
  | "UNKNOWN";

export interface Party {
  id: string;
  name: string;
  role: "COMPANY" | "PERSON" | "AUTHORITY" | "OTHER";
  contactHint?: string;
}

export interface UnknownItem {
  id: string;
  question: string;
  /** Why this matters — shown to the user as "Why I'm asking". */
  reason: string;
  importance: "REQUIRED" | "HELPFUL";
  resolved: boolean;
  answer?: string;
  createdAt: Timestamp;
}

export interface Fact {
  id: string;
  caseId: string;
  statement: string;
  verification: FactVerification;
  confidence: Confidence;
  sourceEvidenceId?: string;
  sourceUrl?: string;
  createdAt: Timestamp;
}

export type EvidenceType = "IMAGE" | "PDF" | "DOCUMENT" | "SCREENSHOT" | "TEXT";
export type EvidenceProcessingStatus = "UPLOADED" | "PROCESSING" | "PROCESSED" | "FAILED";

export interface Evidence {
  id: string;
  caseId: string;
  userId: string;
  fileName: string;
  mimeType: string;
  sizeBytes: number;
  storagePath: string;
  extractedText?: string;
  /** Set when extraction was attempted but no capability existed for this type. */
  extractionNote?: string;
  extractionNoteText?: LocalizedText;
  evidenceType: EvidenceType;
  processingStatus: EvidenceProcessingStatus;
  relatedFactIds: string[];
  createdAt: Timestamp;
}

export type TimelineSource = "USER" | "DOCUMENT" | "SYSTEM" | "EXTERNAL" | "AI_INFERENCE";

export interface TimelineEvent {
  id: string;
  caseId: string;
  date?: Timestamp;
  /** Rendered text. Used directly for user or document content. */
  title: string;
  description: string;
  /** Set when the entry was generated by the system; takes precedence in the UI. */
  titleText?: LocalizedText;
  descriptionText?: LocalizedText;
  source: TimelineSource;
  createdAt: Timestamp;
}

export type ActionType = "INFORMATION" | "RECOMMENDATION" | "DRAFT" | "EXTERNAL_ACTION";

export type ActionStatus =
  | "PENDING"
  | "REQUIRES_APPROVAL"
  | "APPROVED"
  | "IN_PROGRESS"
  | "COMPLETED"
  | "FAILED"
  | "CANCELLED";

/**
 * Delivery state of an external action. Kept separate from ActionStatus so the
 * UI can never imply something was sent when only a draft exists (§25).
 */
export type DeliveryState =
  | "DRAFTED"
  | "APPROVED"
  | "IN_PROGRESS"
  | "SENT"
  | "DELIVERED"
  | "RESPONSE_RECEIVED"
  | "FAILED"
  | "UNKNOWN";

export interface ActionStep {
  id: string;
  caseId: string;
  order: number;
  title: string;
  description: string;
  type: ActionType;
  status: ActionStatus;
  requiresApproval: boolean;
  toolName?: string;
  /** True when the action names a capability that is not connected yet. */
  toolAvailable?: boolean;
  deliveryState?: DeliveryState;
  draft?: ActionDraft;
  dependsOn?: string[];
  createdAt: Timestamp;
  updatedAt: Timestamp;
}

export interface ActionDraft {
  channel: "EMAIL" | "LETTER" | "FORM" | "MESSAGE";
  recipient?: string;
  subject?: string;
  body: string;
  /** Exactly what leaves the user's control if they approve. */
  sharedInformation: string[];
  editedByUser?: boolean;
}

export interface Task {
  id: string;
  caseId: string;
  title: string;
  description?: string;
  /** Set when the task was generated by the system rather than the user. */
  titleText?: LocalizedText;
  descriptionText?: LocalizedText;
  priority: "LOW" | "MEDIUM" | "HIGH";
  dueAt?: Timestamp;
  status: "PENDING" | "COMPLETED" | "CANCELLED";
  assignedTo: "USER" | "AI";
  createdAt: Timestamp;
}

export type ResearchSourceType = "OFFICIAL" | "GOVERNMENT" | "REGULATOR" | "POLICY" | "SECONDARY";

export interface ResearchItem {
  id: string;
  caseId: string;
  question: string;
  finding: string;
  sourceTitle?: string;
  sourceUrl?: string;
  sourceType: ResearchSourceType;
  confidence: Confidence;
  retrievedAt: Timestamp;
}

export interface Case {
  id: string;
  userId: string;

  title: string;
  summary: string;
  originalProblem: string;
  userGoal?: string;

  primaryCategory?: string;
  secondaryCategories?: string[];

  status: CaseStatus;
  riskLevel: RiskLevel;
  /** Catalogue key for the plain-language note about how this case is handled. */
  riskNoteKey?: string;

  involvedParties: Party[];
  unknowns: UnknownItem[];

  currentNextAction?: string;

  parentCaseId?: string;
  childCaseIds?: string[];

  /** Set when the user was asked to confirm resolution. */
  resolutionConfirmedByUser?: boolean;

  /**
   * The language the case was written in, detected at intake. Independent of
   * the interface language: switching the UI never rewrites a case, and the
   * assistant keeps replying in the language the person actually used.
   */
  contentLocale?: string;

  createdAt: Timestamp;
  updatedAt: Timestamp;
}

export type MessageRole = "USER" | "ASSISTANT" | "SYSTEM_NOTE";

export interface CaseMessage {
  id: string;
  caseId: string;
  role: MessageRole;
  content: string;
  /**
   * What this turn changed in the Case, for transparency. Stored as catalogue
   * references so the annotation reads in whichever language the case is
   * viewed in, while the message content itself stays as written.
   */
  appliedChanges?: LocalizedText[];
  createdAt: Timestamp;
}

export type NotificationKind =
  | "INFORMATION_REQUIRED"
  | "APPROVAL_REQUIRED"
  | "DEADLINE"
  | "FOLLOW_UP"
  | "NEW_RESPONSE"
  | "STATUS_CHANGE";

export interface Notification {
  id: string;
  userId: string;
  caseId?: string;
  kind: NotificationKind;
  title: string;
  body: string;
  /** Set when the body is system-generated rather than case content. */
  bodyText?: LocalizedText;
  readAt?: Timestamp;
  createdAt: Timestamp;
}

export type AuditEventType =
  | "CASE_CREATED"
  | "CASE_UPDATED"
  | "FACT_ADDED"
  | "FACT_REMOVED"
  | "EVIDENCE_UPLOADED"
  | "EVIDENCE_PROCESSED"
  | "RESEARCH_COMPLETED"
  | "PLAN_CREATED"
  | "ACTION_DRAFTED"
  | "USER_APPROVED_ACTION"
  | "ACTION_EXECUTED"
  | "ACTION_CANCELLED"
  | "RESPONSE_RECEIVED"
  | "STATUS_CHANGED"
  | "AUTH_FAILURE"
  | "ACCESS_DENIED";

export interface AuditEvent {
  id: string;
  userId?: string;
  caseId?: string;
  type: AuditEventType;
  detail: string;
  createdAt: Timestamp;
}

export interface User {
  id: string;
  email: string;
  displayName?: string;
  /** Only set for the local credential provider; never for federated sign-in. */
  passwordHash?: string;
  createdAt: Timestamp;
}
