/**
 * Demo data provider.
 *
 * Serves the synthetic dataset in `data/demo-dataset.json` so the whole product
 * loop — basket, matching, optimization, price history, alerts — can be run and
 * tested where no live feed is reachable.
 *
 * Everything it emits is flagged `producesRealMarketPrices: false` and carries
 * the source `demo-fixture`. The application uses that flag to show a permanent
 * "this is not real price data" banner, and the final report must not count
 * these chains as covered.
 */

import { readFileSync } from 'node:fs';
import path from 'node:path';
import type { PromotionKind } from '@/lib/domain/promotions';
import type {
  AvailabilityReport,
  FetchOptions,
  PriceDataProvider,
  ProviderBranch,
  ProviderDescriptor,
  ProviderPrice,
  ProviderProduct,
  ProviderPromotion,
  ProviderSnapshot,
} from './types';

export const DEMO_SOURCE = 'demo-fixture';

export interface DemoDatasetProduct {
  id: string;
  barcode: string;
  nameHe: string;
  nameEn: string;
  brand: string;
  category: string;
  basePriceAgorot: number;
}

export interface DemoDatasetBranch {
  id: string;
  chainId: string;
  name: string;
  city: string;
  latitude: number;
  longitude: number;
  supportsDelivery: boolean;
  deliveryFeeAgorot: number | null;
  deliveryMinimumAgorot: number | null;
}

export interface DemoDatasetPrice {
  productId: string;
  branchId: string;
  chainId: string;
  priceAgorot: number;
  observedAt: string;
  promotionId: string | null;
  isMemberPrice: boolean;
}

export interface DemoDatasetPromotion {
  id: string;
  chainId: string;
  branchId: string;
  productId: string;
  kind: PromotionKind;
  description: string;
  buyQuantity: number | null;
  freeQuantity: number | null;
  bundleQuantity: number | null;
  bundlePriceAgorot: number | null;
  percentOff: number | null;
  promoUnitPriceAgorot: number | null;
  minQuantity: number | null;
  requiresMembership: boolean;
  startsAt: string;
  endsAt: string;
}

export interface DemoDataset {
  realMarketData: false;
  referenceNow: string;
  weeksOfHistory: number;
  products: DemoDatasetProduct[];
  branches: DemoDatasetBranch[];
  promotions: DemoDatasetPromotion[];
  prices: DemoDatasetPrice[];
}

let cachedDataset: DemoDataset | null = null;

export const DEMO_DATASET_PATH = path.join(process.cwd(), 'data', 'demo-dataset.json');

export function loadDemoDataset(): DemoDataset {
  if (cachedDataset) return cachedDataset;
  const parsed = JSON.parse(readFileSync(DEMO_DATASET_PATH, 'utf8')) as DemoDataset;
  if (parsed.realMarketData !== false) {
    // A dataset that claims to be real must not be loaded through the demo path.
    throw new Error('demo dataset must declare realMarketData: false');
  }
  cachedDataset = parsed;
  return parsed;
}

export class DemoPriceProvider implements PriceDataProvider {
  readonly descriptor: ProviderDescriptor;
  private readonly dataset: DemoDataset;

  constructor(dataset: DemoDataset = loadDemoDataset()) {
    // Guard here as well as in the loader: a dataset that claims to be real
    // market data must never be served through the demo path, whatever its origin.
    if (dataset.realMarketData !== false) {
      throw new Error('demo provider refuses a dataset that does not declare realMarketData: false');
    }
    this.dataset = dataset;
    this.descriptor = {
      id: 'demo-fixture',
      name: 'Demo dataset (synthetic — not real prices)',
      dataKind: 'demo_fixture',
      supportedChainIds: [...new Set(dataset.branches.map((b) => b.chainId))],
      freshnessSeconds: null,
      rateLimitPerMinute: null,
      requiresCredentials: false,
      legalNotes:
        'Synthetic data generated by scripts/generate-demo-dataset.ts. Contains no real retail prices and carries no licensing restrictions.',
      producesRealMarketPrices: false,
    };
  }

  async checkAvailability(): Promise<AvailabilityReport> {
    return {
      available: true,
      checkedAt: new Date().toISOString(),
      reason: null,
      lastSuccessAt: this.dataset.referenceNow,
    };
  }

  /** The full history the dataset holds, used to seed price history. */
  fullHistory(): DemoDatasetPrice[] {
    return this.dataset.prices;
  }

  async fetchSnapshot(options: FetchOptions = {}): Promise<ProviderSnapshot> {
    return this.snapshotAsOf(null, options);
  }

  /**
   * Snapshot of the dataset as it stood at `asOf`.
   *
   * Seeding replays the dataset week by week through this, so `price_history`
   * is built by the same ingest path that a live provider would use rather than
   * by a separate back-door writer.
   */
  snapshotAsOf(asOf: string | null, options: FetchOptions = {}): ProviderSnapshot {
    const fetchedAt = asOf ?? new Date().toISOString();
    const asOfMs = asOf === null ? Number.POSITIVE_INFINITY : Date.parse(asOf);
    const chainFilter = options.chainIds ? new Set(options.chainIds) : null;

    const branches: ProviderBranch[] = this.dataset.branches
      .filter((b) => !chainFilter || chainFilter.has(b.chainId))
      .map((b) => ({
        externalBranchId: b.id,
        chainId: b.chainId,
        name: b.name,
        city: b.city,
        address: null,
        latitude: b.latitude,
        longitude: b.longitude,
        supportsDelivery: b.supportsDelivery,
        deliveryFeeAgorot: b.deliveryFeeAgorot,
        deliveryMinimumAgorot: b.deliveryMinimumAgorot,
      }));
    const branchIds = new Set(branches.map((b) => b.externalBranchId));

    const products: ProviderProduct[] = this.dataset.products.map((p) => ({
      externalProductId: p.id,
      barcode: p.barcode,
      name: p.nameHe,
      manufacturer: p.brand,
      brand: p.brand,
      category: p.category,
      packageText: null,
      quantity: null,
      unitOfMeasure: null,
    }));

    // Only the most recent observation per (product, branch) is "current".
    const latest = new Map<string, DemoDatasetPrice>();
    for (const price of this.dataset.prices) {
      if (!branchIds.has(price.branchId)) continue;
      if (Date.parse(price.observedAt) > asOfMs) continue;
      const key = `${price.productId}|${price.branchId}`;
      const existing = latest.get(key);
      if (!existing || price.observedAt > existing.observedAt) latest.set(key, price);
    }

    const prices: ProviderPrice[] = [...latest.values()].map((p) => ({
      externalProductId: p.productId,
      externalBranchId: p.branchId,
      chainId: p.chainId,
      priceAgorot: p.priceAgorot,
      currency: 'ILS' as const,
      observedAt: p.observedAt,
      isMemberPrice: p.isMemberPrice,
      availability: 'unknown' as const,
      confidence: 1,
      source: DEMO_SOURCE,
    }));

    const activePromotionIds = new Set(
      [...latest.values()].map((p) => p.promotionId).filter((id): id is string => id !== null),
    );
    const promotions: ProviderPromotion[] = this.dataset.promotions
      .filter((p) => activePromotionIds.has(p.id) && branchIds.has(p.branchId))
      .map((p) => ({
        externalPromotionId: p.id,
        chainId: p.chainId,
        externalBranchId: p.branchId,
        externalProductIds: [p.productId],
        kind: p.kind,
        description: p.description,
        buyQuantity: p.buyQuantity,
        freeQuantity: p.freeQuantity,
        bundleQuantity: p.bundleQuantity,
        bundlePriceAgorot: p.bundlePriceAgorot,
        percentOff: p.percentOff,
        discountAgorot: null,
        promoUnitPriceAgorot: p.promoUnitPriceAgorot,
        minQuantity: p.minQuantity,
        requiresMembership: p.requiresMembership,
        startsAt: p.startsAt,
        endsAt: p.endsAt,
        observedAt: fetchedAt,
        source: DEMO_SOURCE,
      }));

    return {
      providerId: this.descriptor.id,
      fetchedAt,
      branches,
      products,
      prices,
      promotions,
      warnings: ['synthetic_demo_data_not_real_prices'],
      producesRealMarketPrices: false,
    };
  }
}
